# Generated by Django 3.0.2 on 2020-01-30 12:58

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('elo', models.FloatField(default=1500, validators=[django.core.validators.MinValueValidator(1000)])),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('fbLink', models.URLField()),
                ('instLink', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
