# Generated by Django 3.0.2 on 2020-01-31 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200130_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='account_id',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
