# Generated by Django 3.0.2 on 2020-01-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200131_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
